# Generated by Django 2.2 on 2019-04-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_auto_20190428_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=1),
        ),
    ]
