# Generated by Django 2.2 on 2019-04-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0006_auto_20190428_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
    ]
