# Generated by Django 2.2 on 2019-05-04 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0009_auto_20190504_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(default='tag', on_delete=django.db.models.deletion.CASCADE, to='myBlog.Tag'),
        ),
    ]
